# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1281, 811))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(500, 170, 281, 431))
        self.widget.setAcceptDrops(False)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ipEdit = QtWidgets.QLineEdit(self.widget)
        self.ipEdit.setGeometry(QtCore.QRect(30, 100, 51, 20))
        self.ipEdit.setObjectName("ipEdit")
        self.ipEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.ipEdit_2.setGeometry(QtCore.QRect(90, 100, 51, 20))
        self.ipEdit_2.setObjectName("ipEdit_2")
        self.ipEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.ipEdit_3.setGeometry(QtCore.QRect(150, 100, 51, 20))
        self.ipEdit_3.setObjectName("ipEdit_3")
        self.ipEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.ipEdit_4.setGeometry(QtCore.QRect(210, 100, 51, 20))
        self.ipEdit_4.setObjectName("ipEdit_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.networkEdit = QtWidgets.QLineEdit(self.widget)
        self.networkEdit.setGeometry(QtCore.QRect(30, 170, 61, 20))
        self.networkEdit.setObjectName("networkEdit")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.domainEdit = QtWidgets.QLineEdit(self.widget)
        self.domainEdit.setGeometry(QtCore.QRect(30, 230, 231, 20))
        self.domainEdit.setObjectName("domainEdit")
        self.domainButton = QtWidgets.QPushButton(self.widget)
        self.domainButton.setGeometry(QtCore.QRect(150, 170, 101, 31))
        self.domainButton.setObjectName("domainButton")
        self.connectButton = QtWidgets.QPushButton(self.widget)
        self.connectButton.setGeometry(QtCore.QRect(0, 360, 281, 31))
        self.connectButton.setObjectName("connectButton")
        self.userEdit = QtWidgets.QLineEdit(self.widget)
        self.userEdit.setGeometry(QtCore.QRect(30, 300, 231, 20))
        self.userEdit.setObjectName("userEdit")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.newButton = QtWidgets.QPushButton(self.page_2)
        self.newButton.setGeometry(QtCore.QRect(180, 700, 851, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.newButton.setFont(font)
        self.newButton.setObjectName("newButton")
        self.newButton_2 = QtWidgets.QPushButton(self.page_2)
        self.newButton_2.setGeometry(QtCore.QRect(1090, 700, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.newButton_2.setFont(font)
        self.newButton_2.setObjectName("newButton_2")
        self.title1 = QtWidgets.QLabel(self.page_2)
        self.title1.setGeometry(QtCore.QRect(80, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.title1.setFont(font)
        self.title1.setText("")
        self.title1.setAlignment(QtCore.Qt.AlignCenter)
        self.title1.setObjectName("title1")
        self.contents1 = QtWidgets.QLabel(self.page_2)
        self.contents1.setGeometry(QtCore.QRect(80, 40, 1101, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.contents1.setFont(font)
        self.contents1.setText("")
        self.contents1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.contents1.setObjectName("contents1")
        self.username1 = QtWidgets.QLabel(self.page_2)
        self.username1.setGeometry(QtCore.QRect(540, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.username1.setFont(font)
        self.username1.setText("")
        self.username1.setAlignment(QtCore.Qt.AlignCenter)
        self.username1.setObjectName("username1")
        self.time1 = QtWidgets.QLabel(self.page_2)
        self.time1.setGeometry(QtCore.QRect(870, 10, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.time1.setFont(font)
        self.time1.setText("")
        self.time1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time1.setObjectName("time1")
        self.username1_2 = QtWidgets.QLabel(self.page_2)
        self.username1_2.setGeometry(QtCore.QRect(540, 140, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.username1_2.setFont(font)
        self.username1_2.setText("")
        self.username1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.username1_2.setObjectName("username1_2")
        self.contents1_2 = QtWidgets.QLabel(self.page_2)
        self.contents1_2.setGeometry(QtCore.QRect(80, 170, 1101, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.contents1_2.setFont(font)
        self.contents1_2.setText("")
        self.contents1_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.contents1_2.setObjectName("contents1_2")
        self.time1_2 = QtWidgets.QLabel(self.page_2)
        self.time1_2.setGeometry(QtCore.QRect(870, 140, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.time1_2.setFont(font)
        self.time1_2.setText("")
        self.time1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time1_2.setObjectName("time1_2")
        self.title1_2 = QtWidgets.QLabel(self.page_2)
        self.title1_2.setGeometry(QtCore.QRect(80, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.title1_2.setFont(font)
        self.title1_2.setText("")
        self.title1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title1_2.setObjectName("title1_2")
        self.username1_3 = QtWidgets.QLabel(self.page_2)
        self.username1_3.setGeometry(QtCore.QRect(540, 270, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.username1_3.setFont(font)
        self.username1_3.setText("")
        self.username1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.username1_3.setObjectName("username1_3")
        self.contents1_3 = QtWidgets.QLabel(self.page_2)
        self.contents1_3.setGeometry(QtCore.QRect(80, 300, 1101, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.contents1_3.setFont(font)
        self.contents1_3.setText("")
        self.contents1_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.contents1_3.setObjectName("contents1_3")
        self.time1_3 = QtWidgets.QLabel(self.page_2)
        self.time1_3.setGeometry(QtCore.QRect(870, 270, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.time1_3.setFont(font)
        self.time1_3.setText("")
        self.time1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time1_3.setObjectName("time1_3")
        self.title1_3 = QtWidgets.QLabel(self.page_2)
        self.title1_3.setGeometry(QtCore.QRect(80, 270, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.title1_3.setFont(font)
        self.title1_3.setText("")
        self.title1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title1_3.setObjectName("title1_3")
        self.username1_4 = QtWidgets.QLabel(self.page_2)
        self.username1_4.setGeometry(QtCore.QRect(540, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.username1_4.setFont(font)
        self.username1_4.setText("")
        self.username1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.username1_4.setObjectName("username1_4")
        self.contents1_4 = QtWidgets.QLabel(self.page_2)
        self.contents1_4.setGeometry(QtCore.QRect(80, 430, 1101, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.contents1_4.setFont(font)
        self.contents1_4.setText("")
        self.contents1_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.contents1_4.setObjectName("contents1_4")
        self.time1_4 = QtWidgets.QLabel(self.page_2)
        self.time1_4.setGeometry(QtCore.QRect(870, 400, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.time1_4.setFont(font)
        self.time1_4.setText("")
        self.time1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time1_4.setObjectName("time1_4")
        self.title1_4 = QtWidgets.QLabel(self.page_2)
        self.title1_4.setGeometry(QtCore.QRect(80, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.title1_4.setFont(font)
        self.title1_4.setText("")
        self.title1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.title1_4.setObjectName("title1_4")
        self.username1_5 = QtWidgets.QLabel(self.page_2)
        self.username1_5.setGeometry(QtCore.QRect(540, 540, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.username1_5.setFont(font)
        self.username1_5.setText("")
        self.username1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.username1_5.setObjectName("username1_5")
        self.contents1_5 = QtWidgets.QLabel(self.page_2)
        self.contents1_5.setGeometry(QtCore.QRect(80, 570, 1101, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.contents1_5.setFont(font)
        self.contents1_5.setText("")
        self.contents1_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.contents1_5.setObjectName("contents1_5")
        self.time1_5 = QtWidgets.QLabel(self.page_2)
        self.time1_5.setGeometry(QtCore.QRect(870, 540, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.time1_5.setFont(font)
        self.time1_5.setText("")
        self.time1_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time1_5.setObjectName("time1_5")
        self.title1_5 = QtWidgets.QLabel(self.page_2)
        self.title1_5.setGeometry(QtCore.QRect(80, 540, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.title1_5.setFont(font)
        self.title1_5.setText("")
        self.title1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.title1_5.setObjectName("title1_5")
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setGeometry(QtCore.QRect(-3, 510, 1281, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(10, 380, 1281, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.page_2)
        self.line_3.setGeometry(QtCore.QRect(0, 250, 1281, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.page_2)
        self.line_4.setGeometry(QtCore.QRect(0, 120, 1281, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(90, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(100, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit.setGeometry(QtCore.QRect(250, 50, 881, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.page_3)
        self.textEdit.setGeometry(QtCore.QRect(250, 120, 881, 481))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.submitButton = QtWidgets.QPushButton(self.page_3)
        self.submitButton.setGeometry(QtCore.QRect(250, 610, 881, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Network Settings"))
        self.label_2.setText(_translate("MainWindow", "IP ADDRESS"))
        self.label_3.setText(_translate("MainWindow", "Network Port"))
        self.label_4.setText(_translate("MainWindow", "Domain Name"))
        self.domainButton.setText(_translate("MainWindow", "Local Domain"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.label_5.setText(_translate("MainWindow", "UserName"))
        self.newButton.setText(_translate("MainWindow", "New"))
        self.newButton_2.setText(_translate("MainWindow", "Refresh"))
        self.label_6.setText(_translate("MainWindow", "Title :"))
        self.label_7.setText(_translate("MainWindow", "Contents :"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

